# Generated by Django 5.0.3 on 2024-03-14 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libro', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='libro_Usuario',
            fields=[
                ('id_libro_Usuario', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField()),
                ('es_favorito', models.BooleanField()),
                ('actualmente_leyendo', models.BooleanField()),
                ('es_leer_mas_tarde', models.BooleanField()),
                ('es_leido', models.BooleanField()),
                ('calificacion', models.FloatField(default=0)),
                ('id_libro', models.ForeignKey(db_column='id_libro', on_delete=django.db.models.deletion.DO_NOTHING, to='libro.libro')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='user.usuario')),
            ],
        ),
    ]
