# Generated by Django 5.0.3 on 2024-05-02 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_libro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro_usuario',
            name='activo',
        ),
    ]
