# Generated by Django 5.0.3 on 2024-05-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_libro', '0002_remove_libro_usuario_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro_usuario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
