# Generated by Django 5.0.3 on 2024-05-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_libro', '0003_libro_usuario_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro_usuario',
            name='en_biblioteca',
            field=models.BooleanField(default=False),
        ),
    ]
