# Generated by Django 5.0.3 on 2024-03-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_libro_libro_categorias'),
        ('user', '0002_alter_usuario_apellido'),
        ('user_libro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='libros_usuario',
            field=models.ManyToManyField(through='user_libro.libro_Usuario', to='libro.libro'),
        ),
    ]
