# Generated by Django 5.0.3 on 2024-03-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usuario_libros_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='img',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
