
# Generated by Django 5.0.3 on 2024-03-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_libro_libro_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='es_activo',
            field=models.BooleanField(default=True),
        ),
    ]
