
# Generated by Django 5.0.3 on 2024-04-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_libro_es_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='editorial',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='libro',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn10',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn13',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
