
# Generated by Django 5.0.3 on 2024-04-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0004_alter_libro_descripcion_alter_libro_editorial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='isbn10',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn13',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
