
# Generated by Django 5.0.3 on 2024-04-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0006_alter_libro_editorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
