# Generated by Django 5.0.3 on 2024-04-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0007_alter_libro_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fecha',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
