
# Generated by Django 5.0.3 on 2024-04-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0011_alter_libro_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='editorial',
            field=models.TextField(blank=True, null=True),
        ),
    ]
