# Generated by Django 5.0.3 on 2024-05-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0012_alter_libro_editorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
