
# Generated by Django 5.0.3 on 2024-03-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='es_activo',
            field=models.BooleanField(default=True),
        ),
    ]
