# Generated by Django 5.0.3 on 2024-04-16 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_categoria_es_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
