# Generated by Django 5.0.3 on 2024-06-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0005_categoria_sub_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='sub_categoria',
            new_name='parent_categoria_id',
        ),
    ]
