# Generated by Django 5.0.3 on 2024-06-02 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0006_rename_sub_categoria_categoria_parent_categoria_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='parent_categoria_id',
            new_name='parent_categoria',
        ),
    ]
