# Generated by Django 5.0.3 on 2024-03-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('contrasenia', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('appellido1', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('es_admin', models.BooleanField(default=False)),
                ('es_staff', models.BooleanField(default=False)),
            ],
        ),
    ]
