# Generated by Django 5.0.3 on 2024-03-14 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librital', '0002_libro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Libro',
        ),
    ]
