# Generated by Django 5.0.3 on 2024-03-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librital', '0003_delete_libro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Librital',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
